GET http://localhost:3001/api/users

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "sampleUsername",
    "password": "sekret"
}

###
DELETE http://localhost:3003/api/blogs/601d8502d96b83418c411719
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZVVzZXJuYW1lIiwiaWQiOiI2MDFkODRiOGQ5NmI4MzQxOGM0MTE3MTgiLCJpYXQiOjE2MTI1NDczMTV9.HA0qVf0IEFV0M43sPCtzw1ILM3BDZfcyj1cmYOm1c9I

###
PUT http://localhost:3003/api/blogs/6019809ac484d057d891b164
Content-Type: application/json

{
    "likes": 7
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZVVzZXJuYW1lIiwiaWQiOiI2MDFkODRiOGQ5NmI4MzQxOGM0MTE3MTgiLCJpYXQiOjE2MTI1NDczMTV9.HA0qVf0IEFV0M43sPCtzw1ILM3BDZfcyj1cmYOm1c9I

{
    "url": "testUrl222",
    "title": "anka22",
    "author": "sampleNUmber"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "sampleName",
    "username": "sampleUsername",
    "password": "sekret"
}

###
GET http://localhost:3001/info